### ISSUE TITLE
Uncaught Error: file data stream has unexpected number of bytes

### ISSUE THREAD

**Issue by AaronV** [SqrTT/Bart#12]
[Enter steps to reproduce below:]
1. Change branches (triggering a zip upload process form Bart)
2. Changes branches again (before the first zip finishes doing it's thing)

**Atom Version**: 1.8.0
**System**: Mac OS X 10.11.5
**Thrown From**: [Bart](https://github.com/SqrTT/bart) package, v1.2.3
### Stack Trace

Uncaught Error: file data stream has unexpected number of bytes

```
At events.js:141

Error: file data stream has unexpected number of bytes
    at ByteCounter.<anonymous> (/Users/aaronvanderpoel/.atom/packages/Bart/node_modules/yazl/index.js:136:99)
    at emitNone (events.js:72:20)
    at ByteCounter.emit (events.js:166:7)
    at endReadableNT (_stream_readable.js:905:12)
    at doNTCallback2 (node.js:465:9)
    at process._tickCallback (node.js:379:17)
```
### Commands

```
     -1:54 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:54 core:cancel (atom-text-editor.editor.is-focused)
     -1:53.3.0 editor:consolidate-selections (atom-text-editor#bart-password.mini.editor.bart-password.is-focused)
     -1:53.3.0 core:cancel (atom-text-editor#bart-password.mini.editor.bart-password.is-focused)
     -1:46.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:45.5.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:45.5.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:44.8.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:44.8.0 core:cancel (atom-text-editor.editor.is-focused)
     -1:42.8.0 core:save (atom-text-editor.editor.is-focused)
     -1:37 core:paste (atom-text-editor#bart-password.mini.editor.bart-password.is-focused)
     -1:32 core:move-left (atom-text-editor.editor.is-focused)
     -1:31.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:31.2.0 core:save (atom-text-editor.editor.is-focused)
     -1:30.1.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:29.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "linter-jslint",
      "seti-icons",
      "file-type-icons"
    ],
    "themes": [
      "atom-material-ui",
      "atom-material-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Bart, v1.2.3
atom-beautify, v0.29.9
atom-material-syntax, v0.4.6
atom-material-ui, v1.2.13
atom-ternjs, v0.14.2
custom-invisibles, v0.1.2
emmet, v2.4.3
file-icons, v1.7.16
highlight-selected, v0.11.2
language-demandware, v0.1.0
linter, v1.11.14
linter-eslint, v7.2.4
linter-jshint, v2.1.0
linter-json-lint, v0.1.1
minimap, v4.24.7
pigments, v0.31.0
react, v0.15.0
tab-length, v0.1.0
terminal-plus, v0.14.5

# Dev
No dev packages
```

**Comment by SqrTT** [comment]
thanks, for bringing this up, I'll take a look
