### ISSUE TITLE
Failed to activate the Bart package

### ISSUE THREAD

**Issue by edelmtl** [SqrTT/Bart#22]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.15.0 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.12.3
**Thrown From**: [Bart](https://github.com/SqrTT/bart) package 1.5.0

### Stack Trace

Failed to activate the Bart package

```
At Cannot find module 'request'

Error: Cannot find module 'request'
    at Module._resolveFilename (module.js:455:15)
    at Module._resolveFilename (/Users/laurencej/Desktop/APP/Atom.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._resolveFilename (/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/bart-dw/lib/DebuggerConnection.js:11:16)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/bart-dw/lib/Debugger.js:11:27)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
    at /packages/bart-dw/lib/bart.js:16:50)
    at Module._compile (/app.asar/src/native-compile-cache.js:109:30)
    at /app.asar/src/compile-cache.js:216:21)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (/app.asar/src/native-compile-cache.js:50:27)
```

### Commands

```
     -0:49.6.0 application:add-project-folder (input.hidden-input)
     -0:39.6.0 bart:openConfig (input.hidden-input)
     -0:30.7.0 core:copy (atom-notification.fatal.icon.icon-bug.native-key-bindings.has-detail.has-close.has-stack)
```

### Non-Core Packages

```
atom-beautify 0.29.17 
Bart 1.5.0 
```

**Comment by SqrTT** [comment]
thanx for reporting, could you try to reproduce in version 1.6.0?

**Comment by SqrTT** [comment]
I believe this is fixed if no, feel free to reopen the issue.
