### ISSUE TITLE
Uncaught Error: Repository has been destroyed

### ISSUE THREAD

**Issue by SqrTT** [SqrTT/Bart#3]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.7.3
**System**: Ubuntu 14.04.4
**Thrown From**: [Bart](https://github.com/SqrTT/bart) package, v1.1.0
### Stack Trace

Uncaught Error: Repository has been destroyed

```
At /home/sqrtt/.atom/packages/Bart/lib/bart.js:250

Error: Repository has been destroyed
    at GitRepository.module.exports.GitRepository.getRepo (/opt/atom/resources/app.asar/src/git-repository.js:369:15)
    at GitRepository.module.exports.GitRepository.getShortHead (/opt/atom/resources/app.asar/src/git-repository.js:175:19)
    at /home/sqrtt/.atom/packages/Bart/lib/bart.js:59:40
```
### Commands

```
     -0:56.8.0 core:confirm (atom-text-editor.editor.mini.is-focused)
     -0:01.1.0 tree-view:remove-project-folder (span.name.icon.icon-file-directory)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "open-on-github",
      "ascii-art",
      "vim-mode",
      "atom-typescript",
      "linter",
      "jshint",
      "linter-flow",
      "ide-flow",
      "linter-flow-plus",
      "git-control",
      "activate-power-mode",
      "turbo-javascript",
      "node-debugger",
      "atom-jasmine"
    ],
    "themes": [
      "one-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Bart, v1.1.0
Quick-JavaScript, v0.16.0
atom-jshint, v2.0.0
atom-ternjs, v0.14.1
autoclose-html, v0.23.0
autocomplete-html-entities, v0.1.0
docblockr, v0.7.3
flow, v0.5.3
language-demandware, v0.1.0
language-javascript-semantic, v0.2.1
linter-eslint, v7.2.2
linter-jscs, v4.0.0
minimap, v4.23.5
minimap-cursorline, v0.1.0
pigments, v0.26.2

# Dev
No dev packages
```

**Comment by SqrTT** [comment]
fixed in v1.2.0
